// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Android, iOS, macOS, etc. can be added here later if needed.
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDt4h57AhpK79N6EAJAZQ2lJwupSt5mm1Y",
    authDomain: "disciplined-coach-final.firebaseapp.com",
    projectId: "disciplined-coach-final",
    storageBucket: "disciplined-coach-final.firebasestorage.app",
    messagingSenderId: "111451253057",
    appId: "1:111451253057:web:8000e2b6a63391503e19c0",
    measurementId: "G-RYDB4S9TS7"
  );
}
